/**
 * (c) 2013 Xilinx Inc.
 * XREGDB v0.80
 * XREGCHDR v0.15
 *
 * Generated on: 2019-03-04
 *
 * @file: ddr_qos_ctrl.h
 *
 *
 * This file contains confidential and proprietary information
 * of Xilinx, Inc. and is protected under U.S. and
 * international copyright and other intellectual property
 * laws.
 *
 * DISCLAIMER
 * This disclaimer is not a license and does not grant any
 * rights to the materials distributed herewith. Except as
 * otherwise provided in a valid license issued to you by
 * Xilinx, and to the maximum extent permitted by applicable
 * law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
 * WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
 * AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
 * BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
 * INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
 * (2) Xilinx shall not be liable (whether in contract or tort,
 * including negligence, or under any other theory of
 * liability) for any loss or damage of any kind or nature
 * related to, arising under or in connection with these
 * materials, including for any direct, or any indirect,
 * special, incidental, or consequential loss or damage
 * (including loss of data, profits, goodwill, or any type of
 * loss or damage suffered as a result of any action brought
 * by a third party) even if such damage or loss was
 * reasonably foreseeable or Xilinx had been advised of the
 * possibility of the same.
 *
 * CRITICAL APPLICATIONS
 * Xilinx products are not designed or intended to be fail-
 * safe, or for use in any application requiring fail-safe
 * performance, such as life-support or safety devices or
 * systems, Class III medical devices, nuclear facilities,
 * applications related to the deployment of airbags, or any
 * other applications that could lead to death, personal
 * injury, or severe property or environmental damage
 * (individually and collectively, "Critical
 * Applications"). Customer assumes the sole risk and
 * liability of any use of Xilinx products in Critical
 * Applications, subject only to applicable laws and
 * regulations governing limitations on product liability.
 *
 * THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
 * PART OF THIS FILE AT ALL TIMES.
 *
 * Naming Convention: <MODULE>_<REGISTER>[_<FIELD>[_<DESC>]]
 *     <MODULE>       Module name (e.g. can or usb)
 *     <REGISTER>     Register within the current module
 *     [_<FIELD>]     Bit field within a register
 *     [_<DESC>]      Type of bit field define:
 *         SHIFT:     Least significant bit for the field
 *         WIDTH:     Size of field in bites
 *         MASK:      A masking over a range of bits or a bit to
 *                    be used for setting or clearing
 *
 */

#ifndef _DDR_QOS_CTRL_H_
#define _DDR_QOS_CTRL_H_

#ifdef __cplusplus
extern "C" {
#endif

/**
 * DDR_QOS_CTRL Base Address
 */
#define DDR_QOS_CTRL_BASEADDR      0XFD090000

/**
 * Register: DDR_QOS_CTRL_PORT_TYPE
 */
#define DDR_QOS_CTRL_PORT_TYPE    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000000 )

#define DDR_QOS_CTRL_PORT_TYPE_PORT5_TYPE_SHIFT   14
#define DDR_QOS_CTRL_PORT_TYPE_PORT5_TYPE_WIDTH   2
#define DDR_QOS_CTRL_PORT_TYPE_PORT5_TYPE_MASK    0X0000C000

#define DDR_QOS_CTRL_PORT_TYPE_PORT4_TYPE_SHIFT   12
#define DDR_QOS_CTRL_PORT_TYPE_PORT4_TYPE_WIDTH   2
#define DDR_QOS_CTRL_PORT_TYPE_PORT4_TYPE_MASK    0X00003000

#define DDR_QOS_CTRL_PORT_TYPE_PORT3_TYPE_SHIFT   10
#define DDR_QOS_CTRL_PORT_TYPE_PORT3_TYPE_WIDTH   2
#define DDR_QOS_CTRL_PORT_TYPE_PORT3_TYPE_MASK    0X00000C00

#define DDR_QOS_CTRL_PORT_TYPE_PORT2B_TYPE_SHIFT   8
#define DDR_QOS_CTRL_PORT_TYPE_PORT2B_TYPE_WIDTH   2
#define DDR_QOS_CTRL_PORT_TYPE_PORT2B_TYPE_MASK    0X00000300

#define DDR_QOS_CTRL_PORT_TYPE_PORT2R_TYPE_SHIFT   6
#define DDR_QOS_CTRL_PORT_TYPE_PORT2R_TYPE_WIDTH   2
#define DDR_QOS_CTRL_PORT_TYPE_PORT2R_TYPE_MASK    0X000000C0

#define DDR_QOS_CTRL_PORT_TYPE_PORT1B_TYPE_SHIFT   4
#define DDR_QOS_CTRL_PORT_TYPE_PORT1B_TYPE_WIDTH   2
#define DDR_QOS_CTRL_PORT_TYPE_PORT1B_TYPE_MASK    0X00000030

#define DDR_QOS_CTRL_PORT_TYPE_PORT1R_TYPE_SHIFT   2
#define DDR_QOS_CTRL_PORT_TYPE_PORT1R_TYPE_WIDTH   2
#define DDR_QOS_CTRL_PORT_TYPE_PORT1R_TYPE_MASK    0X0000000C

#define DDR_QOS_CTRL_PORT_TYPE_PORT0_TYPE_SHIFT   0
#define DDR_QOS_CTRL_PORT_TYPE_PORT0_TYPE_WIDTH   2
#define DDR_QOS_CTRL_PORT_TYPE_PORT0_TYPE_MASK    0X00000003

/**
 * Register: DDR_QOS_CTRL_QOS_CTRL
 */
#define DDR_QOS_CTRL_QOS_CTRL    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000004 )

#define DDR_QOS_CTRL_QOS_CTRL_APB_ERR_RES_SHIFT   22
#define DDR_QOS_CTRL_QOS_CTRL_APB_ERR_RES_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_APB_ERR_RES_MASK    0X00400000

#define DDR_QOS_CTRL_QOS_CTRL_PORT5_WR_CTRL_SHIFT   21
#define DDR_QOS_CTRL_QOS_CTRL_PORT5_WR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT5_WR_CTRL_MASK    0X00200000

#define DDR_QOS_CTRL_QOS_CTRL_PORT5_HPR_CTRL_SHIFT   20
#define DDR_QOS_CTRL_QOS_CTRL_PORT5_HPR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT5_HPR_CTRL_MASK    0X00100000

#define DDR_QOS_CTRL_QOS_CTRL_PORT5_LPR_CTRL_SHIFT   19
#define DDR_QOS_CTRL_QOS_CTRL_PORT5_LPR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT5_LPR_CTRL_MASK    0X00080000

#define DDR_QOS_CTRL_QOS_CTRL_PORT4_WR_CTRL_SHIFT   18
#define DDR_QOS_CTRL_QOS_CTRL_PORT4_WR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT4_WR_CTRL_MASK    0X00040000

#define DDR_QOS_CTRL_QOS_CTRL_PORT4_HPR_CTRL_SHIFT   17
#define DDR_QOS_CTRL_QOS_CTRL_PORT4_HPR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT4_HPR_CTRL_MASK    0X00020000

#define DDR_QOS_CTRL_QOS_CTRL_PORT4_LPR_CTRL_SHIFT   16
#define DDR_QOS_CTRL_QOS_CTRL_PORT4_LPR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT4_LPR_CTRL_MASK    0X00010000

#define DDR_QOS_CTRL_QOS_CTRL_PORT3_WR_CTRL_SHIFT   15
#define DDR_QOS_CTRL_QOS_CTRL_PORT3_WR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT3_WR_CTRL_MASK    0X00008000

#define DDR_QOS_CTRL_QOS_CTRL_PORT3_HPR_CTRL_SHIFT   14
#define DDR_QOS_CTRL_QOS_CTRL_PORT3_HPR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT3_HPR_CTRL_MASK    0X00004000

#define DDR_QOS_CTRL_QOS_CTRL_PORT3_LPR_CTRL_SHIFT   13
#define DDR_QOS_CTRL_QOS_CTRL_PORT3_LPR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT3_LPR_CTRL_MASK    0X00002000

#define DDR_QOS_CTRL_QOS_CTRL_PORT2_WR_CTRL_SHIFT   12
#define DDR_QOS_CTRL_QOS_CTRL_PORT2_WR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT2_WR_CTRL_MASK    0X00001000

#define DDR_QOS_CTRL_QOS_CTRL_PORT2B_HPR_CTRL_SHIFT   11
#define DDR_QOS_CTRL_QOS_CTRL_PORT2B_HPR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT2B_HPR_CTRL_MASK    0X00000800

#define DDR_QOS_CTRL_QOS_CTRL_PORT2B_LPR_CTRL_SHIFT   10
#define DDR_QOS_CTRL_QOS_CTRL_PORT2B_LPR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT2B_LPR_CTRL_MASK    0X00000400

#define DDR_QOS_CTRL_QOS_CTRL_PORT2R_HPR_CTRL_SHIFT   9
#define DDR_QOS_CTRL_QOS_CTRL_PORT2R_HPR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT2R_HPR_CTRL_MASK    0X00000200

#define DDR_QOS_CTRL_QOS_CTRL_PORT2R_LPR_CTRL_SHIFT   8
#define DDR_QOS_CTRL_QOS_CTRL_PORT2R_LPR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT2R_LPR_CTRL_MASK    0X00000100

#define DDR_QOS_CTRL_QOS_CTRL_PORT1_WR_CTRL_SHIFT   7
#define DDR_QOS_CTRL_QOS_CTRL_PORT1_WR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT1_WR_CTRL_MASK    0X00000080

#define DDR_QOS_CTRL_QOS_CTRL_PORT1B_HPR_CTRL_SHIFT   6
#define DDR_QOS_CTRL_QOS_CTRL_PORT1B_HPR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT1B_HPR_CTRL_MASK    0X00000040

#define DDR_QOS_CTRL_QOS_CTRL_PORT1B_LPR_CTRL_SHIFT   5
#define DDR_QOS_CTRL_QOS_CTRL_PORT1B_LPR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT1B_LPR_CTRL_MASK    0X00000020

#define DDR_QOS_CTRL_QOS_CTRL_PORT1R_HPR_CTRL_SHIFT   4
#define DDR_QOS_CTRL_QOS_CTRL_PORT1R_HPR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT1R_HPR_CTRL_MASK    0X00000010

#define DDR_QOS_CTRL_QOS_CTRL_PORT1R_LPR_CTRL_SHIFT   3
#define DDR_QOS_CTRL_QOS_CTRL_PORT1R_LPR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT1R_LPR_CTRL_MASK    0X00000008

#define DDR_QOS_CTRL_QOS_CTRL_PORT0_WR_CTRL_SHIFT   2
#define DDR_QOS_CTRL_QOS_CTRL_PORT0_WR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT0_WR_CTRL_MASK    0X00000004

#define DDR_QOS_CTRL_QOS_CTRL_PORT0_HPR_CTRL_SHIFT   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT0_HPR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT0_HPR_CTRL_MASK    0X00000002

#define DDR_QOS_CTRL_QOS_CTRL_PORT0_LPR_CTRL_SHIFT   0
#define DDR_QOS_CTRL_QOS_CTRL_PORT0_LPR_CTRL_WIDTH   1
#define DDR_QOS_CTRL_QOS_CTRL_PORT0_LPR_CTRL_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_RD_HPR_THRSLD
 */
#define DDR_QOS_CTRL_RD_HPR_THRSLD    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000008 )

#define DDR_QOS_CTRL_RD_HPR_THRSLD_VALUE_SHIFT   0
#define DDR_QOS_CTRL_RD_HPR_THRSLD_VALUE_WIDTH   7
#define DDR_QOS_CTRL_RD_HPR_THRSLD_VALUE_MASK    0X0000007F

/**
 * Register: DDR_QOS_CTRL_RD_LPR_THRSLD
 */
#define DDR_QOS_CTRL_RD_LPR_THRSLD    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X0000000C )

#define DDR_QOS_CTRL_RD_LPR_THRSLD_VALUE_SHIFT   0
#define DDR_QOS_CTRL_RD_LPR_THRSLD_VALUE_WIDTH   7
#define DDR_QOS_CTRL_RD_LPR_THRSLD_VALUE_MASK    0X0000007F

/**
 * Register: DDR_QOS_CTRL_WR_THRSLD
 */
#define DDR_QOS_CTRL_WR_THRSLD    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000010 )

#define DDR_QOS_CTRL_WR_THRSLD_VALUE_SHIFT   0
#define DDR_QOS_CTRL_WR_THRSLD_VALUE_WIDTH   7
#define DDR_QOS_CTRL_WR_THRSLD_VALUE_MASK    0X0000007F

/**
 * Register: DDR_QOS_CTRL_ZQCS_CTRL0
 */
#define DDR_QOS_CTRL_ZQCS_CTRL0    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000014 )

#define DDR_QOS_CTRL_ZQCS_CTRL0_ENABLE_SHIFT   0
#define DDR_QOS_CTRL_ZQCS_CTRL0_ENABLE_WIDTH   1
#define DDR_QOS_CTRL_ZQCS_CTRL0_ENABLE_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_ZQCS_CTRL1
 */
#define DDR_QOS_CTRL_ZQCS_CTRL1    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000018 )

#define DDR_QOS_CTRL_ZQCS_CTRL1_VSYNC_CNT_SHIFT   0
#define DDR_QOS_CTRL_ZQCS_CTRL1_VSYNC_CNT_WIDTH   4
#define DDR_QOS_CTRL_ZQCS_CTRL1_VSYNC_CNT_MASK    0X0000000F

/**
 * Register: DDR_QOS_CTRL_ZQCS_STATUS
 */
#define DDR_QOS_CTRL_ZQCS_STATUS    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X0000001C )

#define DDR_QOS_CTRL_ZQCS_STATUS_BUSY_SHIFT   0
#define DDR_QOS_CTRL_ZQCS_STATUS_BUSY_WIDTH   1
#define DDR_QOS_CTRL_ZQCS_STATUS_BUSY_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_DDRC_EXT_REFRESH
 */
#define DDR_QOS_CTRL_DDRC_EXT_REFRESH    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000020 )

#define DDR_QOS_CTRL_DDRC_EXT_REFRESH_ENABLE_SHIFT   0
#define DDR_QOS_CTRL_DDRC_EXT_REFRESH_ENABLE_WIDTH   1
#define DDR_QOS_CTRL_DDRC_EXT_REFRESH_ENABLE_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_DDRPHY_SMODE
 */
#define DDR_QOS_CTRL_DDRPHY_SMODE    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000024 )

#define DDR_QOS_CTRL_DDRPHY_SMODE_LP_TRIGGER_SHIFT   5
#define DDR_QOS_CTRL_DDRPHY_SMODE_LP_TRIGGER_WIDTH   1
#define DDR_QOS_CTRL_DDRPHY_SMODE_LP_TRIGGER_MASK    0X00000020

#define DDR_QOS_CTRL_DDRPHY_SMODE_AC_RST_SHIFT   4
#define DDR_QOS_CTRL_DDRPHY_SMODE_AC_RST_WIDTH   1
#define DDR_QOS_CTRL_DDRPHY_SMODE_AC_RST_MASK    0X00000010

#define DDR_QOS_CTRL_DDRPHY_SMODE_VT_TRIGGER_SHIFT   2
#define DDR_QOS_CTRL_DDRPHY_SMODE_VT_TRIGGER_WIDTH   1
#define DDR_QOS_CTRL_DDRPHY_SMODE_VT_TRIGGER_MASK    0X00000004

#define DDR_QOS_CTRL_DDRPHY_SMODE_DLL_MAX_SHIFT   1
#define DDR_QOS_CTRL_DDRPHY_SMODE_DLL_MAX_WIDTH   1
#define DDR_QOS_CTRL_DDRPHY_SMODE_DLL_MAX_MASK    0X00000002

#define DDR_QOS_CTRL_DDRPHY_SMODE_DLL_MIN_SHIFT   0
#define DDR_QOS_CTRL_DDRPHY_SMODE_DLL_MIN_WIDTH   1
#define DDR_QOS_CTRL_DDRPHY_SMODE_DLL_MIN_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_QOS_IRQ_STATUS
 */
#define DDR_QOS_CTRL_QOS_IRQ_STATUS    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000200 )

#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DDRC_WR_POISON_SHIFT   10
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DDRC_WR_POISON_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DDRC_WR_POISON_MASK    0X00000400

#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DDRC_RD_POISON_SHIFT   9
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DDRC_RD_POISON_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DDRC_RD_POISON_MASK    0X00000200

#define DDR_QOS_CTRL_QOS_IRQ_STATUS_MRR_DATA_VALID_SHIFT   8
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_MRR_DATA_VALID_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_MRR_DATA_VALID_MASK    0X00000100

#define DDR_QOS_CTRL_QOS_IRQ_STATUS_PC_COPY_DONE_SHIFT   7
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_PC_COPY_DONE_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_PC_COPY_DONE_MASK    0X00000080

#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DFI_ALT_ERR_SHIFT   6
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DFI_ALT_ERR_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DFI_ALT_ERR_MASK    0X00000040

#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DFI_ALT_ERR_MAX_SHIFT   5
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DFI_ALT_ERR_MAX_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DFI_ALT_ERR_MAX_MASK    0X00000020

#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DFI_ALT_ERR_FTL_SHIFT   4
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DFI_ALT_ERR_FTL_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DFI_ALT_ERR_FTL_MASK    0X00000010

#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DFI_INIT_COMP_SHIFT   3
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DFI_INIT_COMP_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DFI_INIT_COMP_MASK    0X00000008

#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DDRECC_UNCRERR_SHIFT   2
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DDRECC_UNCRERR_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DDRECC_UNCRERR_MASK    0X00000004

#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DDRECC_CORERR_SHIFT   1
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DDRECC_CORERR_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_DDRECC_CORERR_MASK    0X00000002

#define DDR_QOS_CTRL_QOS_IRQ_STATUS_INV_APB_SHIFT   0
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_INV_APB_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_STATUS_INV_APB_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_QOS_IRQ_MASK
 */
#define DDR_QOS_CTRL_QOS_IRQ_MASK    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000204 )

#define DDR_QOS_CTRL_QOS_IRQ_MASK_DDRC_WR_POISON_SHIFT   10
#define DDR_QOS_CTRL_QOS_IRQ_MASK_DDRC_WR_POISON_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_MASK_DDRC_WR_POISON_MASK    0X00000400

#define DDR_QOS_CTRL_QOS_IRQ_MASK_DDRC_RD_POISON_SHIFT   9
#define DDR_QOS_CTRL_QOS_IRQ_MASK_DDRC_RD_POISON_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_MASK_DDRC_RD_POISON_MASK    0X00000200

#define DDR_QOS_CTRL_QOS_IRQ_MASK_MRR_DATA_VALID_SHIFT   8
#define DDR_QOS_CTRL_QOS_IRQ_MASK_MRR_DATA_VALID_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_MASK_MRR_DATA_VALID_MASK    0X00000100

#define DDR_QOS_CTRL_QOS_IRQ_MASK_PC_COPY_DONE_SHIFT   7
#define DDR_QOS_CTRL_QOS_IRQ_MASK_PC_COPY_DONE_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_MASK_PC_COPY_DONE_MASK    0X00000080

#define DDR_QOS_CTRL_QOS_IRQ_MASK_DFI_ALT_ERR_SHIFT   6
#define DDR_QOS_CTRL_QOS_IRQ_MASK_DFI_ALT_ERR_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_MASK_DFI_ALT_ERR_MASK    0X00000040

#define DDR_QOS_CTRL_QOS_IRQ_MASK_DFI_ALT_ERR_MAX_SHIFT   5
#define DDR_QOS_CTRL_QOS_IRQ_MASK_DFI_ALT_ERR_MAX_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_MASK_DFI_ALT_ERR_MAX_MASK    0X00000020

#define DDR_QOS_CTRL_QOS_IRQ_MASK_DFI_ALT_ERR_FTL_SHIFT   4
#define DDR_QOS_CTRL_QOS_IRQ_MASK_DFI_ALT_ERR_FTL_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_MASK_DFI_ALT_ERR_FTL_MASK    0X00000010

#define DDR_QOS_CTRL_QOS_IRQ_MASK_DFI_INIT_COMP_SHIFT   3
#define DDR_QOS_CTRL_QOS_IRQ_MASK_DFI_INIT_COMP_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_MASK_DFI_INIT_COMP_MASK    0X00000008

#define DDR_QOS_CTRL_QOS_IRQ_MASK_DDRECC_UNCRERR_SHIFT   2
#define DDR_QOS_CTRL_QOS_IRQ_MASK_DDRECC_UNCRERR_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_MASK_DDRECC_UNCRERR_MASK    0X00000004

#define DDR_QOS_CTRL_QOS_IRQ_MASK_DDRECC_CORERR_SHIFT   1
#define DDR_QOS_CTRL_QOS_IRQ_MASK_DDRECC_CORERR_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_MASK_DDRECC_CORERR_MASK    0X00000002

#define DDR_QOS_CTRL_QOS_IRQ_MASK_INV_APB_SHIFT   0
#define DDR_QOS_CTRL_QOS_IRQ_MASK_INV_APB_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_MASK_INV_APB_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_QOS_IRQ_ENABLE
 */
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000208 )

#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DDRC_WR_POISON_SHIFT   10
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DDRC_WR_POISON_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DDRC_WR_POISON_MASK    0X00000400

#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DDRC_RD_POISON_SHIFT   9
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DDRC_RD_POISON_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DDRC_RD_POISON_MASK    0X00000200

#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_MRR_DATA_VALID_SHIFT   8
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_MRR_DATA_VALID_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_MRR_DATA_VALID_MASK    0X00000100

#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_PC_COPY_DONE_SHIFT   7
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_PC_COPY_DONE_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_PC_COPY_DONE_MASK    0X00000080

#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DFI_ALT_ERR_SHIFT   6
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DFI_ALT_ERR_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DFI_ALT_ERR_MASK    0X00000040

#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DFI_ALT_ERR_MAX_SHIFT   5
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DFI_ALT_ERR_MAX_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DFI_ALT_ERR_MAX_MASK    0X00000020

#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DFI_ALT_ERR_FTL_SHIFT   4
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DFI_ALT_ERR_FTL_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DFI_ALT_ERR_FTL_MASK    0X00000010

#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DFI_INIT_COMP_SHIFT   3
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DFI_INIT_COMP_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DFI_INIT_COMP_MASK    0X00000008

#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DDRECC_UNCRERR_SHIFT   2
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DDRECC_UNCRERR_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DDRECC_UNCRERR_MASK    0X00000004

#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DDRECC_CORERR_SHIFT   1
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DDRECC_CORERR_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_DDRECC_CORERR_MASK    0X00000002

#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_INV_APB_SHIFT   0
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_INV_APB_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_ENABLE_INV_APB_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_QOS_IRQ_DISABLE
 */
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X0000020C )

#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DDRC_WR_POISON_SHIFT   10
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DDRC_WR_POISON_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DDRC_WR_POISON_MASK    0X00000400

#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DDRC_RD_POISON_SHIFT   9
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DDRC_RD_POISON_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DDRC_RD_POISON_MASK    0X00000200

#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_MRR_DATA_VALID_SHIFT   8
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_MRR_DATA_VALID_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_MRR_DATA_VALID_MASK    0X00000100

#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_PC_COPY_DONE_SHIFT   7
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_PC_COPY_DONE_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_PC_COPY_DONE_MASK    0X00000080

#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DFI_ALT_ERR_SHIFT   6
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DFI_ALT_ERR_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DFI_ALT_ERR_MASK    0X00000040

#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DFI_ALT_ERR_MAX_SHIFT   5
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DFI_ALT_ERR_MAX_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DFI_ALT_ERR_MAX_MASK    0X00000020

#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DFI_ALT_ERR_FTL_SHIFT   4
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DFI_ALT_ERR_FTL_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DFI_ALT_ERR_FTL_MASK    0X00000010

#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DFI_INIT_COMP_SHIFT   3
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DFI_INIT_COMP_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DFI_INIT_COMP_MASK    0X00000008

#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DDRECC_UNCRERR_SHIFT   2
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DDRECC_UNCRERR_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DDRECC_UNCRERR_MASK    0X00000004

#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DDRECC_CORERR_SHIFT   1
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DDRECC_CORERR_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_DDRECC_CORERR_MASK    0X00000002

#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_INV_APB_SHIFT   0
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_INV_APB_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_DISABLE_INV_APB_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_QOS_IRQ_TRIGGER
 */
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000210 )

#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DDRC_WR_POISON_SHIFT   10
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DDRC_WR_POISON_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DDRC_WR_POISON_MASK    0X00000400

#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DDRC_RD_POISON_SHIFT   9
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DDRC_RD_POISON_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DDRC_RD_POISON_MASK    0X00000200

#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_MRR_DATA_VALID_SHIFT   8
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_MRR_DATA_VALID_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_MRR_DATA_VALID_MASK    0X00000100

#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_PC_COPY_DONE_SHIFT   7
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_PC_COPY_DONE_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_PC_COPY_DONE_MASK    0X00000080

#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DFI_ALT_ERR_SHIFT   6
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DFI_ALT_ERR_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DFI_ALT_ERR_MASK    0X00000040

#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DFI_ALT_ERR_MAX_SHIFT   5
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DFI_ALT_ERR_MAX_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DFI_ALT_ERR_MAX_MASK    0X00000020

#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DFI_ALT_ERR_FTL_SHIFT   4
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DFI_ALT_ERR_FTL_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DFI_ALT_ERR_FTL_MASK    0X00000010

#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DFI_INIT_COMP_SHIFT   3
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DFI_INIT_COMP_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DFI_INIT_COMP_MASK    0X00000008

#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DDRECC_UNCRERR_SHIFT   2
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DDRECC_UNCRERR_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DDRECC_UNCRERR_MASK    0X00000004

#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DDRECC_CORERR_SHIFT   1
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DDRECC_CORERR_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_DDRECC_CORERR_MASK    0X00000002

#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_INV_APB_SHIFT   0
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_INV_APB_WIDTH   1
#define DDR_QOS_CTRL_QOS_IRQ_TRIGGER_INV_APB_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_PC_CTRL
 */
#define DDR_QOS_CTRL_PC_CTRL    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000400 )

#define DDR_QOS_CTRL_PC_CTRL_PC_ENABLE_SHIFT   0
#define DDR_QOS_CTRL_PC_CTRL_PC_ENABLE_WIDTH   1
#define DDR_QOS_CTRL_PC_CTRL_PC_ENABLE_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_PC_TOTAL_CYL_CNT
 */
#define DDR_QOS_CTRL_PC_TOTAL_CYL_CNT    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000404 )

#define DDR_QOS_CTRL_PC_TOTAL_CYL_CNT_TOTAL_CYL_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_TOTAL_CYL_CNT_TOTAL_CYL_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_TOTAL_CYL_CNT_TOTAL_CYL_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_0
 */
#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_0    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000408 )

#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_0_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_0_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_0_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_0
 */
#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_0    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X0000040C )

#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_0_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_0_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_0_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_0
 */
#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_0    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000410 )

#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_0_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_0_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_0_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_0
 */
#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_0    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000414 )

#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_0_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_0_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_0_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_0
 */
#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_0    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000418 )

#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_0_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_0_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_0_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_0
 */
#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_0    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X0000041C )

#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_0_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_0_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_0_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_0
 */
#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_0    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000420 )

#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_0_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_0_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_0_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_0
 */
#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_0    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000424 )

#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_0_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_0_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_0_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_1
 */
#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_1    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000428 )

#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_1_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_1_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_1_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_1
 */
#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_1    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X0000042C )

#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_1_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_1_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_1_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_1
 */
#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_1    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000430 )

#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_1_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_1_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_1_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_1
 */
#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_1    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000434 )

#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_1_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_1_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_1_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_1
 */
#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_1    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000438 )

#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_1_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_1_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_1_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_1
 */
#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_1    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X0000043C )

#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_1_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_1_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_1_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_1
 */
#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_1    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000440 )

#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_1_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_1_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_1_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_1
 */
#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_1    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000444 )

#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_1_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_1_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_1_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_2
 */
#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_2    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000448 )

#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_2_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_2_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_2_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_2
 */
#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_2    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X0000044C )

#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_2_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_2_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_2_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_2
 */
#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_2    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000450 )

#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_2_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_2_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_2_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_2
 */
#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_2    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000454 )

#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_2_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_2_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_2_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_2
 */
#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_2    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000458 )

#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_2_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_2_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_2_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_2
 */
#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_2    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X0000045C )

#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_2_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_2_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_2_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_2
 */
#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_2    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000460 )

#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_2_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_2_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_2_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_2
 */
#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_2    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000464 )

#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_2_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_2_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_2_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_3
 */
#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_3    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000468 )

#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_3_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_3_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_3_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_3
 */
#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_3    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X0000046C )

#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_3_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_3_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_3_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_3
 */
#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_3    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000470 )

#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_3_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_3_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_3_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_3
 */
#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_3    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000474 )

#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_3_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_3_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_3_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_3
 */
#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_3    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000478 )

#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_3_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_3_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_3_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_3
 */
#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_3    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X0000047C )

#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_3_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_3_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_3_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_3
 */
#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_3    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000480 )

#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_3_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_3_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_3_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_3
 */
#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_3    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000484 )

#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_3_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_3_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_3_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_4
 */
#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_4    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000488 )

#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_4_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_4_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_4_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_4
 */
#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_4    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X0000048C )

#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_4_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_4_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_4_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_4
 */
#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_4    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000490 )

#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_4_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_4_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_4_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_4
 */
#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_4    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000494 )

#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_4_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_4_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_4_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_4
 */
#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_4    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000498 )

#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_4_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_4_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_4_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_4
 */
#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_4    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X0000049C )

#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_4_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_4_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_4_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_4
 */
#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_4    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X000004A0 )

#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_4_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_4_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_4_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_4
 */
#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_4    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X000004A4 )

#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_4_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_4_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_4_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_5
 */
#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_5    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X000004A8 )

#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_5_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_5_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDCMD_CNT_PORT_5_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_5
 */
#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_5    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X000004AC )

#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_5_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_5_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRCMD_CNT_PORT_5_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_5
 */
#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_5    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X000004B0 )

#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_5_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_5_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDCMD_STL_CNT_PORT_5_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_5
 */
#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_5    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X000004B4 )

#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_5_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_5_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRCMD_STL_CNT_PORT_5_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_5
 */
#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_5    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X000004B8 )

#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_5_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_5_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDDATA_CNT_PORT_5_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_5
 */
#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_5    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X000004BC )

#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_5_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_5_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRDATA_CNT_PORT_5_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_5
 */
#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_5    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X000004C0 )

#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_5_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_5_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_RDDATA_STL_CNT_PORT_5_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_5
 */
#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_5    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X000004C4 )

#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_5_CNT_SHIFT   0
#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_5_CNT_WIDTH   32
#define DDR_QOS_CTRL_PC_WRDATA_STL_CNT_PORT_5_CNT_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_PC_COPY_PERIOD
 */
#define DDR_QOS_CTRL_PC_COPY_PERIOD    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X000004E8 )

#define DDR_QOS_CTRL_PC_COPY_PERIOD_COPY_PERIOD_SHIFT   0
#define DDR_QOS_CTRL_PC_COPY_PERIOD_COPY_PERIOD_WIDTH   32
#define DDR_QOS_CTRL_PC_COPY_PERIOD_COPY_PERIOD_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_DDRC_WR_RAM
 */
#define DDR_QOS_CTRL_DDRC_WR_RAM    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000500 )

#define DDR_QOS_CTRL_DDRC_WR_RAM_EMASA_SHIFT   6
#define DDR_QOS_CTRL_DDRC_WR_RAM_EMASA_WIDTH   1
#define DDR_QOS_CTRL_DDRC_WR_RAM_EMASA_MASK    0X00000040

#define DDR_QOS_CTRL_DDRC_WR_RAM_EMAB_SHIFT   3
#define DDR_QOS_CTRL_DDRC_WR_RAM_EMAB_WIDTH   3
#define DDR_QOS_CTRL_DDRC_WR_RAM_EMAB_MASK    0X00000038

#define DDR_QOS_CTRL_DDRC_WR_RAM_EMAA_SHIFT   0
#define DDR_QOS_CTRL_DDRC_WR_RAM_EMAA_WIDTH   3
#define DDR_QOS_CTRL_DDRC_WR_RAM_EMAA_MASK    0X00000007

/**
 * Register: DDR_QOS_CTRL_DDRC_RD_RAM
 */
#define DDR_QOS_CTRL_DDRC_RD_RAM    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000504 )

#define DDR_QOS_CTRL_DDRC_RD_RAM_EMASA_SHIFT   6
#define DDR_QOS_CTRL_DDRC_RD_RAM_EMASA_WIDTH   1
#define DDR_QOS_CTRL_DDRC_RD_RAM_EMASA_MASK    0X00000040

#define DDR_QOS_CTRL_DDRC_RD_RAM_EMAB_SHIFT   3
#define DDR_QOS_CTRL_DDRC_RD_RAM_EMAB_WIDTH   3
#define DDR_QOS_CTRL_DDRC_RD_RAM_EMAB_MASK    0X00000038

#define DDR_QOS_CTRL_DDRC_RD_RAM_EMAA_SHIFT   0
#define DDR_QOS_CTRL_DDRC_RD_RAM_EMAA_WIDTH   3
#define DDR_QOS_CTRL_DDRC_RD_RAM_EMAA_MASK    0X00000007

/**
 * Register: DDR_QOS_CTRL_DDRC_URGENT
 */
#define DDR_QOS_CTRL_DDRC_URGENT    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000510 )

#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENT_5_SHIFT   13
#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENT_5_WIDTH   1
#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENT_5_MASK    0X00002000

#define DDR_QOS_CTRL_DDRC_URGENT_AWURGENT_5_SHIFT   12
#define DDR_QOS_CTRL_DDRC_URGENT_AWURGENT_5_WIDTH   1
#define DDR_QOS_CTRL_DDRC_URGENT_AWURGENT_5_MASK    0X00001000

#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENT_4_SHIFT   11
#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENT_4_WIDTH   1
#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENT_4_MASK    0X00000800

#define DDR_QOS_CTRL_DDRC_URGENT_AWURGENT_4_SHIFT   10
#define DDR_QOS_CTRL_DDRC_URGENT_AWURGENT_4_WIDTH   1
#define DDR_QOS_CTRL_DDRC_URGENT_AWURGENT_4_MASK    0X00000400

#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENT_3_SHIFT   9
#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENT_3_WIDTH   1
#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENT_3_MASK    0X00000200

#define DDR_QOS_CTRL_DDRC_URGENT_AWURGENT_3_SHIFT   8
#define DDR_QOS_CTRL_DDRC_URGENT_AWURGENT_3_WIDTH   1
#define DDR_QOS_CTRL_DDRC_URGENT_AWURGENT_3_MASK    0X00000100

#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENTR_2_SHIFT   7
#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENTR_2_WIDTH   1
#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENTR_2_MASK    0X00000080

#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENTB_2_SHIFT   6
#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENTB_2_WIDTH   1
#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENTB_2_MASK    0X00000040

#define DDR_QOS_CTRL_DDRC_URGENT_AWURGENT_2_SHIFT   5
#define DDR_QOS_CTRL_DDRC_URGENT_AWURGENT_2_WIDTH   1
#define DDR_QOS_CTRL_DDRC_URGENT_AWURGENT_2_MASK    0X00000020

#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENTR_1_SHIFT   4
#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENTR_1_WIDTH   1
#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENTR_1_MASK    0X00000010

#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENTB_1_SHIFT   3
#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENTB_1_WIDTH   1
#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENTB_1_MASK    0X00000008

#define DDR_QOS_CTRL_DDRC_URGENT_AWURGENT_1_SHIFT   2
#define DDR_QOS_CTRL_DDRC_URGENT_AWURGENT_1_WIDTH   1
#define DDR_QOS_CTRL_DDRC_URGENT_AWURGENT_1_MASK    0X00000004

#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENT_0_SHIFT   1
#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENT_0_WIDTH   1
#define DDR_QOS_CTRL_DDRC_URGENT_ARURGENT_0_MASK    0X00000002

#define DDR_QOS_CTRL_DDRC_URGENT_AWURGENT_0_SHIFT   0
#define DDR_QOS_CTRL_DDRC_URGENT_AWURGENT_0_WIDTH   1
#define DDR_QOS_CTRL_DDRC_URGENT_AWURGENT_0_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_DDRC_QVN_CTRL
 */
#define DDR_QOS_CTRL_DDRC_QVN_CTRL    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000514 )

#define DDR_QOS_CTRL_DDRC_QVN_CTRL_PREALLOC_P2_SHIFT   4
#define DDR_QOS_CTRL_DDRC_QVN_CTRL_PREALLOC_P2_WIDTH   2
#define DDR_QOS_CTRL_DDRC_QVN_CTRL_PREALLOC_P2_MASK    0X00000030

#define DDR_QOS_CTRL_DDRC_QVN_CTRL_PREALLOC_P1_SHIFT   2
#define DDR_QOS_CTRL_DDRC_QVN_CTRL_PREALLOC_P1_WIDTH   2
#define DDR_QOS_CTRL_DDRC_QVN_CTRL_PREALLOC_P1_MASK    0X0000000C

#define DDR_QOS_CTRL_DDRC_QVN_CTRL_EN_P2_SHIFT   1
#define DDR_QOS_CTRL_DDRC_QVN_CTRL_EN_P2_WIDTH   1
#define DDR_QOS_CTRL_DDRC_QVN_CTRL_EN_P2_MASK    0X00000002

#define DDR_QOS_CTRL_DDRC_QVN_CTRL_EN_P1_SHIFT   0
#define DDR_QOS_CTRL_DDRC_QVN_CTRL_EN_P1_WIDTH   1
#define DDR_QOS_CTRL_DDRC_QVN_CTRL_EN_P1_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_DDRC_MRR_STATUS
 */
#define DDR_QOS_CTRL_DDRC_MRR_STATUS    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000518 )

#define DDR_QOS_CTRL_DDRC_MRR_STATUS_VALID_CNT_SHIFT   1
#define DDR_QOS_CTRL_DDRC_MRR_STATUS_VALID_CNT_WIDTH   3
#define DDR_QOS_CTRL_DDRC_MRR_STATUS_VALID_CNT_MASK    0X0000000E

#define DDR_QOS_CTRL_DDRC_MRR_STATUS_VALID_SHIFT   0
#define DDR_QOS_CTRL_DDRC_MRR_STATUS_VALID_WIDTH   1
#define DDR_QOS_CTRL_DDRC_MRR_STATUS_VALID_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_DDRC_MRR_DATA0
 */
#define DDR_QOS_CTRL_DDRC_MRR_DATA0    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X0000051C )

#define DDR_QOS_CTRL_DDRC_MRR_DATA0_LSB_SHIFT   0
#define DDR_QOS_CTRL_DDRC_MRR_DATA0_LSB_WIDTH   32
#define DDR_QOS_CTRL_DDRC_MRR_DATA0_LSB_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_DDRC_MRR_DATA1
 */
#define DDR_QOS_CTRL_DDRC_MRR_DATA1    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000520 )

#define DDR_QOS_CTRL_DDRC_MRR_DATA1_MSB_SHIFT   0
#define DDR_QOS_CTRL_DDRC_MRR_DATA1_MSB_WIDTH   32
#define DDR_QOS_CTRL_DDRC_MRR_DATA1_MSB_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_DDRC_MRR_DATA2
 */
#define DDR_QOS_CTRL_DDRC_MRR_DATA2    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000524 )

#define DDR_QOS_CTRL_DDRC_MRR_DATA2_ECC_SHIFT   0
#define DDR_QOS_CTRL_DDRC_MRR_DATA2_ECC_WIDTH   8
#define DDR_QOS_CTRL_DDRC_MRR_DATA2_ECC_MASK    0X000000FF

/**
 * Register: DDR_QOS_CTRL_DDRC_MRR_DATA3
 */
#define DDR_QOS_CTRL_DDRC_MRR_DATA3    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000528 )

#define DDR_QOS_CTRL_DDRC_MRR_DATA3_LSB_SHIFT   0
#define DDR_QOS_CTRL_DDRC_MRR_DATA3_LSB_WIDTH   32
#define DDR_QOS_CTRL_DDRC_MRR_DATA3_LSB_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_DDRC_MRR_DATA4
 */
#define DDR_QOS_CTRL_DDRC_MRR_DATA4    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X0000052C )

#define DDR_QOS_CTRL_DDRC_MRR_DATA4_MSB_SHIFT   0
#define DDR_QOS_CTRL_DDRC_MRR_DATA4_MSB_WIDTH   32
#define DDR_QOS_CTRL_DDRC_MRR_DATA4_MSB_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_DDRC_MRR_DATA5
 */
#define DDR_QOS_CTRL_DDRC_MRR_DATA5    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000530 )

#define DDR_QOS_CTRL_DDRC_MRR_DATA5_ECC_SHIFT   0
#define DDR_QOS_CTRL_DDRC_MRR_DATA5_ECC_WIDTH   8
#define DDR_QOS_CTRL_DDRC_MRR_DATA5_ECC_MASK    0X000000FF

/**
 * Register: DDR_QOS_CTRL_DDRC_MRR_DATA6
 */
#define DDR_QOS_CTRL_DDRC_MRR_DATA6    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000534 )

#define DDR_QOS_CTRL_DDRC_MRR_DATA6_LSB_SHIFT   0
#define DDR_QOS_CTRL_DDRC_MRR_DATA6_LSB_WIDTH   32
#define DDR_QOS_CTRL_DDRC_MRR_DATA6_LSB_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_DDRC_MRR_DATA7
 */
#define DDR_QOS_CTRL_DDRC_MRR_DATA7    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000538 )

#define DDR_QOS_CTRL_DDRC_MRR_DATA7_MSB_SHIFT   0
#define DDR_QOS_CTRL_DDRC_MRR_DATA7_MSB_WIDTH   32
#define DDR_QOS_CTRL_DDRC_MRR_DATA7_MSB_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_DDRC_MRR_DATA8
 */
#define DDR_QOS_CTRL_DDRC_MRR_DATA8    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X0000053C )

#define DDR_QOS_CTRL_DDRC_MRR_DATA8_ECC_SHIFT   0
#define DDR_QOS_CTRL_DDRC_MRR_DATA8_ECC_WIDTH   8
#define DDR_QOS_CTRL_DDRC_MRR_DATA8_ECC_MASK    0X000000FF

/**
 * Register: DDR_QOS_CTRL_DDRC_MRR_DATA9
 */
#define DDR_QOS_CTRL_DDRC_MRR_DATA9    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000540 )

#define DDR_QOS_CTRL_DDRC_MRR_DATA9_LSB_SHIFT   0
#define DDR_QOS_CTRL_DDRC_MRR_DATA9_LSB_WIDTH   32
#define DDR_QOS_CTRL_DDRC_MRR_DATA9_LSB_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_DDRC_MRR_DATA10
 */
#define DDR_QOS_CTRL_DDRC_MRR_DATA10    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000544 )

#define DDR_QOS_CTRL_DDRC_MRR_DATA10_MSB_SHIFT   0
#define DDR_QOS_CTRL_DDRC_MRR_DATA10_MSB_WIDTH   32
#define DDR_QOS_CTRL_DDRC_MRR_DATA10_MSB_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_DDRC_MRR_DATA11
 */
#define DDR_QOS_CTRL_DDRC_MRR_DATA11    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000548 )

#define DDR_QOS_CTRL_DDRC_MRR_DATA11_ECC_SHIFT   0
#define DDR_QOS_CTRL_DDRC_MRR_DATA11_ECC_WIDTH   8
#define DDR_QOS_CTRL_DDRC_MRR_DATA11_ECC_MASK    0X000000FF

/**
 * Register: DDR_QOS_CTRL_XPD0_REG0
 */
#define DDR_QOS_CTRL_XPD0_REG0    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000600 )

#define DDR_QOS_CTRL_XPD0_REG0_PRE_LOAD_SHIFT   0
#define DDR_QOS_CTRL_XPD0_REG0_PRE_LOAD_WIDTH   32
#define DDR_QOS_CTRL_XPD0_REG0_PRE_LOAD_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_XPD0_REG1
 */
#define DDR_QOS_CTRL_XPD0_REG1    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000604 )

#define DDR_QOS_CTRL_XPD0_REG1_EXPECTED_SHIFT   0
#define DDR_QOS_CTRL_XPD0_REG1_EXPECTED_WIDTH   32
#define DDR_QOS_CTRL_XPD0_REG1_EXPECTED_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_XPD0_CTRL0
 */
#define DDR_QOS_CTRL_XPD0_CTRL0    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000608 )

#define DDR_QOS_CTRL_XPD0_CTRL0_DELAY_SPARE_SHIFT   25
#define DDR_QOS_CTRL_XPD0_CTRL0_DELAY_SPARE_WIDTH   5
#define DDR_QOS_CTRL_XPD0_CTRL0_DELAY_SPARE_MASK    0X3E000000

#define DDR_QOS_CTRL_XPD0_CTRL0_CMP_SEL_SHIFT   24
#define DDR_QOS_CTRL_XPD0_CTRL0_CMP_SEL_WIDTH   1
#define DDR_QOS_CTRL_XPD0_CTRL0_CMP_SEL_MASK    0X01000000

#define DDR_QOS_CTRL_XPD0_CTRL0_DELAY_CELL_TYPE_SHIFT   19
#define DDR_QOS_CTRL_XPD0_CTRL0_DELAY_CELL_TYPE_WIDTH   5
#define DDR_QOS_CTRL_XPD0_CTRL0_DELAY_CELL_TYPE_MASK    0X00F80000

#define DDR_QOS_CTRL_XPD0_CTRL0_DELAY_VT_TYPE_SHIFT   17
#define DDR_QOS_CTRL_XPD0_CTRL0_DELAY_VT_TYPE_WIDTH   2
#define DDR_QOS_CTRL_XPD0_CTRL0_DELAY_VT_TYPE_MASK    0X00060000

#define DDR_QOS_CTRL_XPD0_CTRL0_DELAY_VALUE_SHIFT   6
#define DDR_QOS_CTRL_XPD0_CTRL0_DELAY_VALUE_WIDTH   11
#define DDR_QOS_CTRL_XPD0_CTRL0_DELAY_VALUE_MASK    0X0001FFC0

#define DDR_QOS_CTRL_XPD0_CTRL0_PATH_SEL_SHIFT   0
#define DDR_QOS_CTRL_XPD0_CTRL0_PATH_SEL_WIDTH   6
#define DDR_QOS_CTRL_XPD0_CTRL0_PATH_SEL_MASK    0X0000003F

/**
 * Register: DDR_QOS_CTRL_XPD0_CTRL1
 */
#define DDR_QOS_CTRL_XPD0_CTRL1    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X0000060C )

#define DDR_QOS_CTRL_XPD0_CTRL1_CLK_SPARE_SHIFT   12
#define DDR_QOS_CTRL_XPD0_CTRL1_CLK_SPARE_WIDTH   4
#define DDR_QOS_CTRL_XPD0_CTRL1_CLK_SPARE_MASK    0X0000F000

#define DDR_QOS_CTRL_XPD0_CTRL1_CLK_PHASE_SEL_SHIFT   10
#define DDR_QOS_CTRL_XPD0_CTRL1_CLK_PHASE_SEL_WIDTH   2
#define DDR_QOS_CTRL_XPD0_CTRL1_CLK_PHASE_SEL_MASK    0X00000C00

#define DDR_QOS_CTRL_XPD0_CTRL1_CLK_VT_TYPE_SHIFT   8
#define DDR_QOS_CTRL_XPD0_CTRL1_CLK_VT_TYPE_WIDTH   2
#define DDR_QOS_CTRL_XPD0_CTRL1_CLK_VT_TYPE_MASK    0X00000300

#define DDR_QOS_CTRL_XPD0_CTRL1_CLK_CELL_TYPE_SHIFT   6
#define DDR_QOS_CTRL_XPD0_CTRL1_CLK_CELL_TYPE_WIDTH   2
#define DDR_QOS_CTRL_XPD0_CTRL1_CLK_CELL_TYPE_MASK    0X000000C0

#define DDR_QOS_CTRL_XPD0_CTRL1_CLK_INSERT_DLY_SHIFT   2
#define DDR_QOS_CTRL_XPD0_CTRL1_CLK_INSERT_DLY_WIDTH   4
#define DDR_QOS_CTRL_XPD0_CTRL1_CLK_INSERT_DLY_MASK    0X0000003C

#define DDR_QOS_CTRL_XPD0_CTRL1_CLK_SEL_SHIFT   0
#define DDR_QOS_CTRL_XPD0_CTRL1_CLK_SEL_WIDTH   2
#define DDR_QOS_CTRL_XPD0_CTRL1_CLK_SEL_MASK    0X00000003

/**
 * Register: DDR_QOS_CTRL_XPD0_CTRL2
 */
#define DDR_QOS_CTRL_XPD0_CTRL2    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000614 )

#define DDR_QOS_CTRL_XPD0_CTRL2_CTRL_SPARE_SHIFT   1
#define DDR_QOS_CTRL_XPD0_CTRL2_CTRL_SPARE_WIDTH   2
#define DDR_QOS_CTRL_XPD0_CTRL2_CTRL_SPARE_MASK    0X00000006

#define DDR_QOS_CTRL_XPD0_CTRL2_ENABLE_SHIFT   0
#define DDR_QOS_CTRL_XPD0_CTRL2_ENABLE_WIDTH   1
#define DDR_QOS_CTRL_XPD0_CTRL2_ENABLE_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_XPD0_CTRL3
 */
#define DDR_QOS_CTRL_XPD0_CTRL3    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000618 )

#define DDR_QOS_CTRL_XPD0_CTRL3_DCYCLE_CNT_VALUE_SHIFT   3
#define DDR_QOS_CTRL_XPD0_CTRL3_DCYCLE_CNT_VALUE_WIDTH   12
#define DDR_QOS_CTRL_XPD0_CTRL3_DCYCLE_CNT_VALUE_MASK    0X00007FF8

#define DDR_QOS_CTRL_XPD0_CTRL3_DCYCLE_HIGH_LOW_SHIFT   2
#define DDR_QOS_CTRL_XPD0_CTRL3_DCYCLE_HIGH_LOW_WIDTH   1
#define DDR_QOS_CTRL_XPD0_CTRL3_DCYCLE_HIGH_LOW_MASK    0X00000004

#define DDR_QOS_CTRL_XPD0_CTRL3_DCYCLE_CNT_CLR_SHIFT   1
#define DDR_QOS_CTRL_XPD0_CTRL3_DCYCLE_CNT_CLR_WIDTH   1
#define DDR_QOS_CTRL_XPD0_CTRL3_DCYCLE_CNT_CLR_MASK    0X00000002

#define DDR_QOS_CTRL_XPD0_CTRL3_DCYCLE_START_SHIFT   0
#define DDR_QOS_CTRL_XPD0_CTRL3_DCYCLE_START_WIDTH   1
#define DDR_QOS_CTRL_XPD0_CTRL3_DCYCLE_START_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_XPD0_SOFT_RST
 */
#define DDR_QOS_CTRL_XPD0_SOFT_RST    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X0000061C )

#define DDR_QOS_CTRL_XPD0_SOFT_RST_CLK0_SHIFT   0
#define DDR_QOS_CTRL_XPD0_SOFT_RST_CLK0_WIDTH   1
#define DDR_QOS_CTRL_XPD0_SOFT_RST_CLK0_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_XPD0_STAT
 */
#define DDR_QOS_CTRL_XPD0_STAT    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000620 )

#define DDR_QOS_CTRL_XPD0_STAT_CMP_RESULT_SHIFT   1
#define DDR_QOS_CTRL_XPD0_STAT_CMP_RESULT_WIDTH   1
#define DDR_QOS_CTRL_XPD0_STAT_CMP_RESULT_MASK    0X00000002

#define DDR_QOS_CTRL_XPD0_STAT_CMP_DONE_SHIFT   0
#define DDR_QOS_CTRL_XPD0_STAT_CMP_DONE_WIDTH   1
#define DDR_QOS_CTRL_XPD0_STAT_CMP_DONE_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_XPD1_REG0
 */
#define DDR_QOS_CTRL_XPD1_REG0    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000624 )

#define DDR_QOS_CTRL_XPD1_REG0_PRE_LOAD_SHIFT   0
#define DDR_QOS_CTRL_XPD1_REG0_PRE_LOAD_WIDTH   32
#define DDR_QOS_CTRL_XPD1_REG0_PRE_LOAD_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_XPD1_REG1
 */
#define DDR_QOS_CTRL_XPD1_REG1    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000628 )

#define DDR_QOS_CTRL_XPD1_REG1_EXPECTED_SHIFT   0
#define DDR_QOS_CTRL_XPD1_REG1_EXPECTED_WIDTH   32
#define DDR_QOS_CTRL_XPD1_REG1_EXPECTED_MASK    0XFFFFFFFF

/**
 * Register: DDR_QOS_CTRL_XPD1_CTRL0
 */
#define DDR_QOS_CTRL_XPD1_CTRL0    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X0000062C )

#define DDR_QOS_CTRL_XPD1_CTRL0_DELAY_SPARE_SHIFT   25
#define DDR_QOS_CTRL_XPD1_CTRL0_DELAY_SPARE_WIDTH   5
#define DDR_QOS_CTRL_XPD1_CTRL0_DELAY_SPARE_MASK    0X3E000000

#define DDR_QOS_CTRL_XPD1_CTRL0_CMP_SEL_SHIFT   24
#define DDR_QOS_CTRL_XPD1_CTRL0_CMP_SEL_WIDTH   1
#define DDR_QOS_CTRL_XPD1_CTRL0_CMP_SEL_MASK    0X01000000

#define DDR_QOS_CTRL_XPD1_CTRL0_DELAY_CELL_TYPE_SHIFT   19
#define DDR_QOS_CTRL_XPD1_CTRL0_DELAY_CELL_TYPE_WIDTH   5
#define DDR_QOS_CTRL_XPD1_CTRL0_DELAY_CELL_TYPE_MASK    0X00F80000

#define DDR_QOS_CTRL_XPD1_CTRL0_DELAY_VT_TYPE_SHIFT   17
#define DDR_QOS_CTRL_XPD1_CTRL0_DELAY_VT_TYPE_WIDTH   2
#define DDR_QOS_CTRL_XPD1_CTRL0_DELAY_VT_TYPE_MASK    0X00060000

#define DDR_QOS_CTRL_XPD1_CTRL0_DELAY_VALUE_SHIFT   6
#define DDR_QOS_CTRL_XPD1_CTRL0_DELAY_VALUE_WIDTH   11
#define DDR_QOS_CTRL_XPD1_CTRL0_DELAY_VALUE_MASK    0X0001FFC0

#define DDR_QOS_CTRL_XPD1_CTRL0_PATH_SEL_SHIFT   0
#define DDR_QOS_CTRL_XPD1_CTRL0_PATH_SEL_WIDTH   6
#define DDR_QOS_CTRL_XPD1_CTRL0_PATH_SEL_MASK    0X0000003F

/**
 * Register: DDR_QOS_CTRL_XPD1_CTRL1
 */
#define DDR_QOS_CTRL_XPD1_CTRL1    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000630 )

#define DDR_QOS_CTRL_XPD1_CTRL1_CLK_SPARE_SHIFT   12
#define DDR_QOS_CTRL_XPD1_CTRL1_CLK_SPARE_WIDTH   4
#define DDR_QOS_CTRL_XPD1_CTRL1_CLK_SPARE_MASK    0X0000F000

#define DDR_QOS_CTRL_XPD1_CTRL1_CLK_PHASE_SEL_SHIFT   10
#define DDR_QOS_CTRL_XPD1_CTRL1_CLK_PHASE_SEL_WIDTH   2
#define DDR_QOS_CTRL_XPD1_CTRL1_CLK_PHASE_SEL_MASK    0X00000C00

#define DDR_QOS_CTRL_XPD1_CTRL1_CLK_VT_TYPE_SHIFT   8
#define DDR_QOS_CTRL_XPD1_CTRL1_CLK_VT_TYPE_WIDTH   2
#define DDR_QOS_CTRL_XPD1_CTRL1_CLK_VT_TYPE_MASK    0X00000300

#define DDR_QOS_CTRL_XPD1_CTRL1_CLK_CELL_TYPE_SHIFT   6
#define DDR_QOS_CTRL_XPD1_CTRL1_CLK_CELL_TYPE_WIDTH   2
#define DDR_QOS_CTRL_XPD1_CTRL1_CLK_CELL_TYPE_MASK    0X000000C0

#define DDR_QOS_CTRL_XPD1_CTRL1_CLK_INSERT_DLY_SHIFT   2
#define DDR_QOS_CTRL_XPD1_CTRL1_CLK_INSERT_DLY_WIDTH   4
#define DDR_QOS_CTRL_XPD1_CTRL1_CLK_INSERT_DLY_MASK    0X0000003C

#define DDR_QOS_CTRL_XPD1_CTRL1_CLK_SEL_SHIFT   0
#define DDR_QOS_CTRL_XPD1_CTRL1_CLK_SEL_WIDTH   2
#define DDR_QOS_CTRL_XPD1_CTRL1_CLK_SEL_MASK    0X00000003

/**
 * Register: DDR_QOS_CTRL_XPD1_CTRL2
 */
#define DDR_QOS_CTRL_XPD1_CTRL2    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000634 )

#define DDR_QOS_CTRL_XPD1_CTRL2_CTRL_SPARE_SHIFT   1
#define DDR_QOS_CTRL_XPD1_CTRL2_CTRL_SPARE_WIDTH   2
#define DDR_QOS_CTRL_XPD1_CTRL2_CTRL_SPARE_MASK    0X00000006

#define DDR_QOS_CTRL_XPD1_CTRL2_ENABLE_SHIFT   0
#define DDR_QOS_CTRL_XPD1_CTRL2_ENABLE_WIDTH   1
#define DDR_QOS_CTRL_XPD1_CTRL2_ENABLE_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_XPD1_CTRL3
 */
#define DDR_QOS_CTRL_XPD1_CTRL3    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000638 )

#define DDR_QOS_CTRL_XPD1_CTRL3_DCYCLE_CNT_VALUE_SHIFT   3
#define DDR_QOS_CTRL_XPD1_CTRL3_DCYCLE_CNT_VALUE_WIDTH   12
#define DDR_QOS_CTRL_XPD1_CTRL3_DCYCLE_CNT_VALUE_MASK    0X00007FF8

#define DDR_QOS_CTRL_XPD1_CTRL3_DCYCLE_HIGH_LOW_SHIFT   2
#define DDR_QOS_CTRL_XPD1_CTRL3_DCYCLE_HIGH_LOW_WIDTH   1
#define DDR_QOS_CTRL_XPD1_CTRL3_DCYCLE_HIGH_LOW_MASK    0X00000004

#define DDR_QOS_CTRL_XPD1_CTRL3_DCYCLE_CNT_CLR_SHIFT   1
#define DDR_QOS_CTRL_XPD1_CTRL3_DCYCLE_CNT_CLR_WIDTH   1
#define DDR_QOS_CTRL_XPD1_CTRL3_DCYCLE_CNT_CLR_MASK    0X00000002

#define DDR_QOS_CTRL_XPD1_CTRL3_DCYCLE_START_SHIFT   0
#define DDR_QOS_CTRL_XPD1_CTRL3_DCYCLE_START_WIDTH   1
#define DDR_QOS_CTRL_XPD1_CTRL3_DCYCLE_START_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_XPD1_SOFT_RST
 */
#define DDR_QOS_CTRL_XPD1_SOFT_RST    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X0000063C )

#define DDR_QOS_CTRL_XPD1_SOFT_RST_CLK0_SHIFT   0
#define DDR_QOS_CTRL_XPD1_SOFT_RST_CLK0_WIDTH   1
#define DDR_QOS_CTRL_XPD1_SOFT_RST_CLK0_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_XPD1_STAT
 */
#define DDR_QOS_CTRL_XPD1_STAT    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000640 )

#define DDR_QOS_CTRL_XPD1_STAT_CMP_RESULT_SHIFT   1
#define DDR_QOS_CTRL_XPD1_STAT_CMP_RESULT_WIDTH   1
#define DDR_QOS_CTRL_XPD1_STAT_CMP_RESULT_MASK    0X00000002

#define DDR_QOS_CTRL_XPD1_STAT_CMP_DONE_SHIFT   0
#define DDR_QOS_CTRL_XPD1_STAT_CMP_DONE_WIDTH   1
#define DDR_QOS_CTRL_XPD1_STAT_CMP_DONE_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_DDR_CLK_CTRL
 */
#define DDR_QOS_CTRL_DDR_CLK_CTRL    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000700 )

#define DDR_QOS_CTRL_DDR_CLK_CTRL_CLKACT_SHIFT   0
#define DDR_QOS_CTRL_DDR_CLK_CTRL_CLKACT_WIDTH   1
#define DDR_QOS_CTRL_DDR_CLK_CTRL_CLKACT_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_DDR_DCD_CTRL
 */
#define DDR_QOS_CTRL_DDR_DCD_CTRL    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000704 )

#define DDR_QOS_CTRL_DDR_DCD_CTRL_RST_SHIFT   0
#define DDR_QOS_CTRL_DDR_DCD_CTRL_RST_WIDTH   1
#define DDR_QOS_CTRL_DDR_DCD_CTRL_RST_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_DDRPHY_CTRL
 */
#define DDR_QOS_CTRL_DDRPHY_CTRL    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000708 )

#define DDR_QOS_CTRL_DDRPHY_CTRL_BYP_MODE_SHIFT   0
#define DDR_QOS_CTRL_DDRPHY_CTRL_BYP_MODE_WIDTH   1
#define DDR_QOS_CTRL_DDRPHY_CTRL_BYP_MODE_MASK    0X00000001

/**
 * Register: DDR_QOS_CTRL_DDRC_RETRY_RAM
 */
#define DDR_QOS_CTRL_DDRC_RETRY_RAM    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X0000070C )

#define DDR_QOS_CTRL_DDRC_RETRY_RAM_EMASA_SHIFT   6
#define DDR_QOS_CTRL_DDRC_RETRY_RAM_EMASA_WIDTH   1
#define DDR_QOS_CTRL_DDRC_RETRY_RAM_EMASA_MASK    0X00000040

#define DDR_QOS_CTRL_DDRC_RETRY_RAM_EMAB_SHIFT   3
#define DDR_QOS_CTRL_DDRC_RETRY_RAM_EMAB_WIDTH   3
#define DDR_QOS_CTRL_DDRC_RETRY_RAM_EMAB_MASK    0X00000038

#define DDR_QOS_CTRL_DDRC_RETRY_RAM_EMAA_SHIFT   0
#define DDR_QOS_CTRL_DDRC_RETRY_RAM_EMAA_WIDTH   3
#define DDR_QOS_CTRL_DDRC_RETRY_RAM_EMAA_MASK    0X00000007

/**
 * Register: DDR_QOS_CTRL_DDR_QOS_ECO
 */
#define DDR_QOS_CTRL_DDR_QOS_ECO    ( ( DDR_QOS_CTRL_BASEADDR ) + 0X00000800 )

#define DDR_QOS_CTRL_DDR_QOS_ECO_VAL_SHIFT   0
#define DDR_QOS_CTRL_DDR_QOS_ECO_VAL_WIDTH   32
#define DDR_QOS_CTRL_DDR_QOS_ECO_VAL_MASK    0XFFFFFFFF

#ifdef __cplusplus
}
#endif


#endif /* _DDR_QOS_CTRL_H_ */

